### ISSUE TITLE
Fix printer email configuration

### ISSUE THREAD

**Issue by sunnysideofthescreen** [cloyne/common-electronics#11]
Emailing to printer is no longer working. @mitar halp pleez. 

See issue below:

> This is the mail system at host mail.cloyne.net.
> 
> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.

**Comment by mitar** [comment]
This is useless quote of the issue. :-) The only important part is the one about DKIM signature mismatch. :-)

**Comment by sunnysideofthescreen** [comment]
Less useless than me in the issue... Worry about this on Friday mi!

On Feb 17, 2016, at 12:39 AM, Mitar notifications@github.com wrote:

This is useless quote of the issue. :-) The only important part is the one
about DKIM signature mismatch. :-)

**Comment by mitar** [comment]
So, what is the whole error message?

**Comment by mitar** [comment]
Tacking this in https://github.com/cloyne/network/issues/76.
