### ISSUE TITLE
Fix the duplex issue on the printer

### ISSUE THREAD

**Issue by mitar** [cloyne/common-electronics#12]
This is really getting annoyed.
- http://h20564.www2.hp.com/hpsc/doc/public/display?docId=c03338388
- http://www.pcworld.com/article/227252/how_to_fix_and_avoid_printer_paper_jams.html

**Comment by mitar** [comment]
We should check if there are any small pieces of paper stuck somewhere.

We could also just get a serviceperson to come and check it out. It is probably cheaper than buying a new printer.

**Comment by mitar** [comment]
Here are some past results about printer fixing and suggestions for various services you can order to get it fixed:

http://micronet-at-uc-berkeley.840177.n3.nabble.com/template/NamlServlet.jtp?macro=search_page&node=840177&query=printer+repair&sort=date

I also got this response;

> I sometimes found tiny bits of paper in unusual places in a printer with that symptom.

**Comment by sunnysideofthescreen** [comment]
As per the most recent printer related motion (passed 4/10/16):
-passed $540 to get technician to fix our current printer
-James is going to investigate printer rental opportunities (to bring back on the 4/17/2016)

Progress!!

**Comment by clohard** [comment]
It is still a work in progress =( A technician came but the printer has started having some of the same issues. Apparently **a firmware update is needed**

**Comment by clohard** [comment]
Printer error log is showing late paper feed during duplex operation. Possibly rollers slipping when moving paper?? Technician replaced duplex fuser and rollers on 5/3/16.

**Comment by mitar** [comment]
I upgraded firmware from 2302786_433717 (3.2.3) to 2307851_000043 (3.7.01).

I also upgrade OS level from HP FutureSmart 2 to HP FutureSmart 3. This should give us more features. But I do not see anything which would fix our hardware issues. :-)

**Comment by mitar** [comment]
I printed a test with duplex and it worked for 10 pages without issues.

**Comment by clohard** [comment]
Robert @ california printer repair came to address jamming. Took apart printer, cleaned stuff and re-oiled rollers. Worked perfect after. Will keep an eye on it but at this point issue is considered closed
